# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f39c5814312f85788702cb7807b5688d0977ebe1c3b8bd1cbd1c21e992ebacce5ac7674b3febcb7e6fe82c90af19de707473c56dfd481a7d6bbba596288c592

test:
  secret_key_base: f05bf531510f19b70fe91d33132aff2a8d81f27bbdbd8ddf57bf0f326d5792ddbca81f175e0047ead68ef78d5b9aa96faf4bece5282a39db21a1a165478e6cba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
